#####################
# Basic Information #
#####################
homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - !secret trusted_networks
hassio:

##############
# Automation #
##############
alert: !include alerts.yaml
automation: !include automations.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
rest_command:
  google_backup:
    url: !secret google_backup_url
    timeout: '300'
script: !include scripts.yaml
timer: !include timers.yaml
python_script:

############
# Calendar #
############
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

##########
# Camera #
##########
camera: !include cameras.yaml
stream:

#########
# Cover #
#########
cover: !include cover.yaml

########
# HACS #
########
config:
frontend:
  themes: !include_dir_merge_named themes

##########
# Health #
##########
iqvia:
  zip_code: !secret pollen_zip_code
  monitored_conditions:
    - allergy_index_today
    - allergy_index_tomorrow

######################
# History Components #
######################
history: !include history.yaml
influxdb:
  host: localhost
  port: 8086
  database: !secret influx_db
  username: !secret  influx_un
  password: !secret http_password
  default_measurement: state
logbook: !include logbook.yaml
recorder:

#######
# Hub #
#######
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
octoprint:
  host: !secret OctoIP
  api_key: !secret OctoAPI
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret network_key
  device_config: !include zwave_device_config.yaml

################
# Media Player #
################
media_player:
  - platform: yamaha_musiccast
    host: !secret living_room_yamaha
  # - platform: yamaha_musiccast
  #   host: !secret loft_yamaha
  - platform: volumio
    host: !secret volumiohost
    port: 3000
spotify:
  client_id: !secret  spotify_client_id
  client_secret: !secret spotify_client_secret

##############
# Irrigation #
##############
rachio:
  api_key: !secret rachio_api_key

################
# Organization #
################
group: !include groups.yaml
scene: !include scenes.yaml

#########
# Other #
#########
api:
http:
  base_url: !secret base_url
mobile_app:
system_health:

#################
# Notifications #
#################
notify:
  - platform: html5 
    name: chrome_push_notification
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret nicole_email

###########
# Network #
###########
ssdp:
zeroconf:
discovery:
  ignore:
    - roku

######################
# Presence Detection #
######################
map:
person:

###########
# Sensor #
###########
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

###########
# Switch  #
###########
fan: !include fans.yaml
switch: !include switches.yaml
light: !include lights.yaml

#####################
# System Monitoring #
#####################
pi_hole:
  - host: 'localhost:4865'
fastdotcom:
  scan_interval:
    minutes: 60
speedtestdotnet:
  scan_interval:
    minutes: 65
  monitored_conditions:
    - ping
    - download
    - upload

######################
# Weather Components #
######################
sun:
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily