###############
# MQTT Lights #
###############
# Shower
- platform: mqtt
  name: "Bathroom Shower"
  state_topic: "stat/MB_Shower_light/POWER"
  command_topic: "cmnd/MB_Shower_light/POWER"
  availability_topic: "tele/MB_Shower_light/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Exahust Fan
- platform: mqtt
  name: "Exhaust Fan"
  state_topic: "stat/MB_Exhaust_Fan/POWER"
  command_topic: "cmnd/MB_Exhaust_Fan/POWER"
  availability_topic: "tele/MB_Exhaust_Fan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Bedroom Lights
- platform: mqtt
  name: "Bedroom Light Switch"
  state_topic: "stat/BedroomDimmer/POWER"
  command_topic: "cmnd/BedroomDimmer/POWER"
  availability_topic: "tele/BedroomDimmer/LWT"
  brightness_state_topic: "stat/BedroomDimmer/RESULT"
  brightness_command_topic: "cmnd/BedroomDimmer/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Bedroom Entry Light"
  state_topic: "stat/BedroomEntry/POWER"
  command_topic: "cmnd/BedroomEntry/POWER"
  availability_topic: "tele/BedroomEntry/LWT"
  brightness_state_topic: "stat/BedroomEntry/RESULT"
  brightness_command_topic: "cmnd/BedroomEntry/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Bathroom Vanity Light"
  state_topic: "stat/BathroomVanity/POWER"
  command_topic: "cmnd/BathroomVanity/POWER"
  availability_topic: "tele/BathroomVanity/LWT"
  brightness_state_topic: "stat/BathroomVanity/RESULT"
  brightness_command_topic: "cmnd/BathroomVanity/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Bedroom Closet Light Switch"
  state_topic: "stat/MB_closetlight_shelly/POWER"
  command_topic: "cmnd/MB_closetlight_shelly/POWER"
  availability_topic: "tele/MB_closetlight_shelly/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Dining Room Lights
- platform: mqtt
  name: "Dining Room Light"
  state_topic: "stat/DiningRoom/POWER"
  command_topic: "cmnd/DiningRoom/POWER"
  availability_topic: "tele/DiningRoom/LWT"
  brightness_state_topic: "stat/DiningRoom/RESULT"
  brightness_command_topic: "cmnd/DiningRoom/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Gym Lights
- platform: mqtt
  name: "Gym Light Switch"
  state_topic: "stat/GymLight/POWER"
  command_topic: "cmnd/GymLight/POWER"
  availability_topic: "tele/GymLight/LWT"
  brightness_state_topic: "stat/GymLight/RESULT"
  brightness_command_topic: "cmnd/GymLight/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Loft Lights
- platform: mqtt
  name: "Desk Light Switch"
  state_topic: "stat/DeskLight/POWER"
  command_topic: "cmnd/DeskLight/POWER"
  availability_topic: "tele/DeskLight/LWT"
  brightness_state_topic: "stat/BDeskLight/RESULT"
  brightness_command_topic: "cmnd/DeskLight/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Alcove Light Switch"
  state_topic: "stat/LoftAlcoveLight/POWER"
  command_topic: "cmnd/LoftAlcoveLight/POWER"
  availability_topic: "tele/LoftAlcoveLight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Half Bath Switch"
  state_topic: "stat/HalfBath/POWER"
  command_topic: "cmnd/HalfBath/POWER"
  availability_topic: "tele/HalfBath/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Hall Bath Switch"
  state_topic: "stat/HallBathLight/POWER"
  command_topic: "cmnd/HallBathLight/POWER"
  availability_topic: "tele/HallBathLight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Network Closet Light"
  state_topic: "stat/NetworkCloset/POWER"
  command_topic: "cmnd/NetworkCloset/POWER"
  availability_topic: "tele/NetworkCloset/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  # Loft Fan
- platform: mqtt
  name: "Loft Fan Light"
  state_topic: "stat/LoftFan/POWER1"
  # value_template: "{{ value_json.POWER1 }}"
  command_topic: "cmnd/LoftFan/POWER1"
  availability_topic: "tele/LoftFan/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Hallway Lights
- platform: mqtt
  name: "Hallway Lights MQTT"
  state_topic: "stat/sonoffHall3Way/POWER1"
  command_topic: "cmnd/sonoffHall3Way/EVENT"
  availability_topic: "tele/sonoffHall3Way/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Kitchen Overhead Light
- platform: mqtt
  name: "Kitchen OverheadLights mqtt"
  state_topic: "stat/KitchenLights3W/POWER1"
  command_topic: "cmnd/KitchenLights3W/EVENT"
  availability_topic: "tele/KitchenLights3W/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Unused"
  state_topic: "stat/PierLights/POWER"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/PierLights/POWER"
  availability_topic: "tele/PierLights/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
# Flood lights RGBWW
- platform: mqtt
  name: "Flood Light 1"
  command_topic: "cmnd/Flood1/POWER"
  state_topic: "tele/Flood1/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood1/LWT"
  brightness_command_topic: "cmnd/Flood1/Dimmer"
  brightness_state_topic: "tele/Flood1/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood1/CT"
  color_temp_state_topic: "tele/Flood1/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood1/Color2"
  rgb_state_topic: "tele/Flood1/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood1/Scheme"
  effect_state_topic: "tele/Flood1/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Flood Light 2"
  command_topic: "cmnd/Flood2/POWER"
  state_topic: "tele/Flood2/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood2/LWT"
  brightness_command_topic: "cmnd/Flood2/Dimmer"
  brightness_state_topic: "tele/Flood2/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood2/CT"
  color_temp_state_topic: "tele/Flood2/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood2/Color2"
  rgb_state_topic: "tele/Flood2/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood2/Scheme"
  effect_state_topic: "tele/Flood2/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Flood Light 3"
  command_topic: "cmnd/Flood3/POWER"
  state_topic: "tele/Flood3/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood3/LWT"
  brightness_command_topic: "cmnd/Flood3/Dimmer"
  brightness_state_topic: "tele/Flood3/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood3/CT"
  color_temp_state_topic: "tele/Flood3/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood3/Color2"
  rgb_state_topic: "tele/Flood3/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood3/Scheme"
  effect_state_topic: "tele/Flood3/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
- platform: mqtt
  name: "Pond Light"
  command_topic: "cmnd/Flood4/POWER"
  state_topic: "tele/Flood4/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/Flood4/LWT"
  brightness_command_topic: "cmnd/Flood4/Dimmer"
  brightness_state_topic: "tele/Flood4/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/Flood4/CT"
  color_temp_state_topic: "tele/Flood4/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/Flood4/Color2"
  rgb_state_topic: "tele/Flood4/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/Flood4/Scheme"
  effect_state_topic: "tele/Flood4/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
###################
# Template Lights #
###################
- platform: template
  lights:
    hallway_lights:
      friendly_name: Hallway Lights
      value_template: '{{ is_state("light.hallway_lights_mqtt", "on") }}'
      turn_on:
        - condition: state
          entity_id: light.hallway_lights_mqtt
          state: 'off'
        - service: light.turn_on
          entity_id: light.hallway_lights_mqtt
      turn_off:
        - condition: state
          entity_id: light.hallway_lights_mqtt
          state: 'on'
        - service: light.turn_off
          entity_id: light.hallway_lights_mqtt
    kitchen_overhead_lights:
      friendly_name: Kitchen Overhead Lights
      value_template: '{{ is_state("light.kitchen_overheadlights_mqtt", "on") }}'
      turn_on:
        - condition: state
          entity_id: light.kitchen_overheadlights_mqtt
          state: 'off'
        - service: light.turn_on
          entity_id: light.kitchen_overheadlights_mqtt
      turn_off:
        - condition: state
          entity_id: light.kitchen_overheadlights_mqtt
          state: 'on'
        - service: light.turn_off
          entity_id: light.kitchen_overheadlights_mqtt